spring:
  datasource:
    username: user
    url: jdbc:h2:mem:dcbapp
    driverClassName: org.h2.Driver
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: 'false'

    hibernate:
      ddl-auto: update
    show-sql: true

twilio:
  account_sid: ACfd8a86c7521720896fad19d39bc6f522
  token: 7a48f8a823e4dbbd0960a9e25e10820a
  trial_number: +14849897916

server:
  port: 8089
